export const ADDLOANINITIATION_DETAIL = 'ADDLOANINITIATION_DETAIL';
export const UPDATELOANINITIATION_DETAIL = 'UPDATELOANINITIATION_DETAIL';
export const UPDATE_CLIENT_DETAIL = 'UPDATE_CLIENT_DETAIL';
export const UPDATENESTED_CLIENT_DETAIL = 'UPDATENESTED_CLIENT_DETAIL';
export const DELETE_CLIENT_DETAIL = 'DELETE_CLIENT_DETAIL';
export const DELETENESTED_CLIENT_DETAIL = 'DELETENESTED_CLIENT_DETAIL';
export const DELETELOANINITIATION_DETAIL = 'DELETELOANINITIATION_DETAIL';
export const DELETEADDRESSNESTED_CLIENT_DETAIL = 'DELETEADDRESSNESTED_CLIENT_DETAIL';