export const ADDLOANINITIATION_DETAIL = 'ADDLOANINITIATION_DETAIL';
export const UPDATELOANINITIATION_DETAIL = 'UPDATELOANINITIATION_DETAIL';
export const DELETELOANINITIATION_DETAIL = 'DELETELOANINITIATION_DETAIL';