export const PDSTAGES = 'PDSTAGES';
export const UPDATEPDSTAGES = 'UPDATEPDSTAGES';
export const UPDATEPDMODULE = 'UPDATEPDMODULE';
export const UPDATEPDSUBMODULE = 'UPDATEPDSUBMODULE';
export const UPDATEPDPAGE = 'UPDATEPDPAGE';
export const UPDATEPDSUBSTAGE = 'UPDATEPDSUBSTAGE';
