export const ADDPD_DETAIL = 'ADDPD_DETAIL';
export const UPDATEPD_DETAIL = 'UPDATEPD_DETAIL';
export const DELETEPD_DETAIL = 'DELETEPD_DETAIL';
export const ADD_TRAVEL_DETAILS = 'ADD_TRAVEL_DETAILS';
export const UPDATE_TRAVEL_DETAILS = 'UPDATE_TRAVEL_DETAILS';
export const DELETE_TRAVEL_DETAILS = 'DELETE_TRAVEL_DETAILS';
export const DELETE_OFFICERTRAVEL_DETAILS = 'DELETE_OFFICERTRAVEL_DETAILS';