export const language = [
  {
    en: {
      str_login: 'Login',
      str_logindesc: 'Please enter your User ID and Password',
      str_userid: 'USER ID',
      str_useridholder: 'User ID',
      str_password: 'PASSWORD',
      str_passwordholder: 'Password',
      str_forgotpassword: 'Forgot Password ?',
      str_businessloan: 'Business Loan',
      str_terms: 'Terms',
      str_and: 'and',
      str_version: 'Version',
      str_termsdesc: 'By continuing you agree to our ',
      str_privacypolicy: 'Privacy policy',
      str_errlogin: 'Please Enter Valid Details',
      str_leadcreation: 'Lead Creation',
      str_leadapproval: 'Lead Approval',
      str_basicdetails: 'Basic Details',
      str_customercatg: 'CUSTOMER CATEGORY',
      str_firstname: 'FIRST NAME',
      str_middlename: 'MIDDLE NAME',
      str_lastname: 'LAST NAME',
      str_mobilenumber: 'MOBILE NUMBER',
      str_next: 'NEXT',
      str_submit: 'SUBMIT',
      str_businessdetails: 'Business Details',
      str_filter: 'Filter',
      str_sortby: 'SORT BY',
      str_creationdate: 'Creation Date',
      str_lto: 'Latest to Oldest',
      str_otl: 'Oldest to Latest',
      str_status: 'Status',
      str_statuscap: 'STATUS',
      str_cdcaps: 'CREATION DATE',
      str_leadtype: 'LEAD TYPE',
      str_agentname: 'AGENT NAME',
      str_from: 'FROM',
      str_to: 'TO',
      str_ageingcap: 'AGEING',
      str_operator: 'OPERATOR',
      str_age: 'AGE',
      str_clearfilters: 'Clear Filters',
      str_apply: 'APPLY',
      str_businessname: 'BUSINESS NAME',
      str_industrytype: 'INDUSTRY TYPE',
      str_businessturnover: 'INCOME/BUSINESS TURNOVER (MONTHLY)',
      str_businessvintage: 'BUSINESS VINTAGE',
      str_year: 'YEAR',
      str_months: 'MONTHS',
      str_loandetails: 'Loan Details',
      str_loantype: 'LOAN TYPE',
      str_loanpurpose: 'LOAN PURPOSE',
      str_loanamountmultiple: "LOAN AMOUNT (MULTIPLE OF 5000's)",
      str_leadtype: 'LEAD TYPE',
      str_phtcapture: 'Photo capture and geo tagging',
      str_capturecustpht: 'CAPTURE CUSTOMER PHOTO',
      str_gpslocation: 'GPS LOCATION',
      str_preview: 'Preview',
      str_retake: 'Re-Take/Upload',
      str_delete: 'Delete',
      str_details: 'Details',
      str_deletephoto: 'Delete Photo!',
      str_deletephotodesc: 'Are you sure you want to delete this photo?',
      str_cancel: 'Cancel',
      str_yesdelete: 'Yes,Delete',
      str_error: 'Error',
      str_ok: 'Ok',
      str_errFirstname: 'Please Enter FIRST NAME',
      str_errMiddlename: 'Please Enter MIDDLE NAME',
      str_errLastname: 'Please Enter LAST NAME',
      str_errMobileNumber: 'Please Enter MOBILE NUMBER',
      str_errvalidMobileNumber: 'Please Enter Valid MOBILE NUMBER',
      str_errCustCatg: 'Please Select CUSTOMER CATEGORY',
      str_plsenter: 'Please Enter ',
      str_plsentervalid: 'Please Enter Valid ',
      str_plsselect: 'Please Select ',
      str_mulfive: 'in Multiple of 5000 ',
      str_leadmanagement: 'Lead Management',
      str_leadapprovalstatus: 'Lead Status',
      str_customername: 'Customer Name',
      str_leadid: 'Lead ID',
      str_leadtype: 'Lead Type',
      str_loantype: 'Loan Type',
      str_creationdate: 'Creation Date',
      str_completiondate: 'Completion Date',
      str_completiontime: 'Completion Time',
      str_userid: 'User ID',
      str_username: 'User Name',
      str_ageing: 'Ageing',
      str_leaddetails: 'Lead Details',
      str_leadapprovalstatuss: 'Lead Approval Status',
      str_approvername: 'Approver Name',
      str_loanamount: 'Loan Amount',
      str_captureddetails: 'Capture Details',
      str_leadapprovals: 'Lead Approval',
      str_leadlog: 'Lead Log',
      str_initiateloanapplication: 'Initiate Loan Application',
      str_leadcreation: 'Lead Creation',
      str_errorimage: 'Please Capture Image',
      str_appconfig: 'App Configuration',
      str_enterinstid: 'Enter Institution ID',
      str_enterchallengecode: 'Enter Challenge Code',
      eng_unableToConnectToServer: 'Unable to connect to server',
      str_instRegistered: 'Institution ID registered successfully',
      str_setmpin: 'Set MPIN',
      str_setupmpin: 'Please Setup MPIN',
      str_entermpin: 'ENTER MPIN',
      str_confirmmpin: 'CONFIRM MPIN',
      str_loginviauserid: 'Login via User ID',
      str_plsenteractv: 'Please Enter your Activation Code',
      str_actvcode: 'ACTIVATION CODE',
      str_cancel: 'Cancel',
      str_proceed: 'Proceed',
      str_actvsuccess: 'Activation Successful',
      str_reassign: 'Re-Assign',
      str_leadapproval: 'Lead Approval',
      str_leadstatus: 'LEAD STATUS',
      str_approvercomment: 'APPROVER COMMENT',
      str_leadowner: 'LEAD OWNER',
      str_reason: 'REASON',
      str_reassignedto: 'RE-ASSIGNED TO',
      str_loanapplication: 'Loan Application',
      str_applicationNumber: 'Application Number',
      str_applicationStatus: 'Application Status',
      str_enterbank: 'Please Enter Instituion ID',
      str_enterchallenge: 'Please Enter Challenge Code',
      str_entervalidbank: 'Please Enter Valid Institution ID',
      str_entervalidchallenge: 'Please Enter Valid Challenge Code',
      str_cbresponseheader: 'CB Check (CB Response)',
      str_accholdername: 'Account Holder Name',
      str_cb: 'Credit Bureau',
      str_dt: 'Date & Time',
      str_cbs: 'CB Score',
      str_cbsd: 'CB BRE Decision',
      str_Cbreport: 'CB Report',
      str_preview: 'Preview',
      str_productId: 'Product ID',
      str_cbbrerules: 'CB BRE Rules',
      str_cbscore: 'CB Score',
      str_cbtoal: 'Total Outstanding Allowed Limit',
      str_cbdpddays: 'DPD Days',
      str_cbodamount: 'Overdue Amount',
      str_cbalc: 'Active Lenders Count',
      str_cbmace: 'Maximun allowed credit enquiries',
      str_cbloanstatus: 'Loan Status',
      str_cbotherstatus: 'Other Status',
      str_cannotlessthan: 'Cannot be less than',
      str_cannotgreaterthan: 'Cannot be greater than',
      str_errinternet: 'Internet is not Connected',
      str_errinternetimage: 'Internet is not Connected so Unable to load Image',
      str_previous: 'PREVIOUS',

      str_profileshort: 'PROFILE SHORT',
      str_addressdetail: 'Address Details',
      str_addaddressbutton: 'Add Address',
    },
    ta: {
      first: 'comment allez vous',
      second: 'je vais bien',
      eng_unableToConnectToServer: 'Unable to connect to server',
    },
  },
];
