export const language = [{
    en: {
        str_login: 'Login',
        str_logindesc: 'Please enter your User ID and Password',
        str_userid: 'USER ID',
        str_useridholder: 'User ID',
        str_password: 'PASSWORD',
        str_passwordholder: 'Password',
        str_forgotpassword: 'Forgot Password ?',
        str_businessloan: 'Business Loan',
        str_terms: 'Terms',
        str_and: 'and',
        str_version: 'Version',
        str_termsdesc: 'By continuing you agree to our ',
        str_privacypolicy: 'Privacy policy',
        str_errlogin: 'Please Enter Valid Details',
        str_leadcreation: 'Lead Creation',
        str_basicdetails: 'Basic Details',
        str_customercatg: 'CUSTOMER CATEGORY',
        str_firstname: 'FIRST NAME',
        str_middlename: 'MIDDLE NAME',
        str_lastname: 'LAST NAME',
        str_mobilenumber: 'MOBILE NUMBER',
        str_next:'NEXT',
        str_businessdetails: 'Business Details',
        str_filter  : 'Filter',
        str_sortby : 'SORT BY',
        str_creationdate : 'Creation Date',
        str_lto : 'Latest to Oldest',
        str_otl : 'Oldest to Latest',
        str_status : 'Status',
        str_statuscap : 'STATUS',
        str_cdcaps : 'CREATION DATE',
        str_leadtype : 'LEAD TYPE',
        str_from : 'FROM',
        str_to : 'TO',
        str_ageingcap : 'AGEING',
        str_operator : 'OPERATOR',
        str_age : 'AGE',
        str_clearfilters : 'Clear Filters',
        str_apply : 'APPLY',
        str_leadmanagement : 'Lead Management',
        str_leadapprovalstatus : 'Lead Status',
        str_customername : 'Customer Name',
        str_leadid : 'Lead ID',
        str_leadtype : 'Lead Type',
        str_creationdate : 'Creation Date',
        str_completiondate : 'Completion Date',
        str_ageing : 'Ageing',
        str_leaddetails : 'Lead Details',
        str_leadapprovalstatuss : 'Lead Approval Status',
        str_approvername : 'Approver Name',
        str_loanamount : 'Loan Amount',
        str_captureddetails : 'Capture Details',
        str_leadapprovals : 'Lead Approval',
        str_leadlog : 'Lead Log',
        str_initiateloanapplication : 'Initiate Loan Application',
      },
      ta: {
        first: 'comment allez vous',
        second: 'je vais bien',
        eng_unableToConnectToServer: 'Unable to connect to server'
      },
}]
  
