export const language = [{
    en: {
        str_login: 'Login',
        str_logindesc: 'Please enter your User ID and Password',
        str_userid: 'USER ID',
        str_useridholder: 'User ID',
        str_password: 'PASSWORD',
        str_passwordholder: 'Password',
        str_forgotpassword: 'Forgot Password ?',
        str_businessloan: 'Business Loan',
        str_terms: 'Terms',
        str_and: 'and',
        str_version: 'Version',
        str_termsdesc: 'By continuing you agree to our ',
        str_privacypolicy: 'Privacy policy',
        str_errlogin: 'Please Enter Valid Details',
        str_leadcreation: 'Lead Creation',
        str_basicdetails: 'Basic Details',
        str_customercatg: 'CUSTOMER CATEGORY',
        str_firstname: 'FIRST NAME',
        str_middlename: 'MIDDLE NAME',
        str_lastname: 'LAST NAME',
        str_mobilenumber: 'MOBILE NUMBER',
        str_next:'NEXT',
        str_submit:'SUBMIT',
        str_businessdetails: 'Business Details',
        str_filter  : 'Filter',
        str_sortby : 'SORT BY',
        str_creationdate : 'Creation Date',
        str_lto : 'Latest to Oldest',
        str_otl : 'Oldest to Latest',
        str_status : 'Status',
        str_statuscap : 'STATUS',
        str_cdcaps : 'CREATION DATE',
        str_leadtype : 'LEAD TYPE',
        str_from : 'FROM',
        str_to : 'TO',
        str_ageingcap : 'AGEING',
        str_operator : 'OPERATOR',
        str_age : 'AGE',
        str_clearfilters : 'Clear Filters',
        str_apply : 'APPLY',
        str_businessname: 'BUSINESS NAME',
        str_industrytype: 'INDUSTRY TYPE',
        str_businessturnover: 'INCOME/BUSINESS TURNOVER (MONTHLY)',
        str_businessvintage: 'BUSINESS VINTAGE',
        str_year: 'YEAR',
        str_months: 'MONTHS',
        str_loandetails: 'Loan Details',
        str_loantype: 'LOAN TYPE',
        str_loanpurpose: 'LOAN PURPOSE',
        str_loanamountmultiple: "LOAN AMOUNT (MULTIPLE OF 5000's)",
        str_leadtype: 'LEAD TYPE',
        str_phtcapture: 'Photo capture and geo tagging',
        str_capturecustpht: 'CAPTURE CUSTOMER PHOTO',
        str_gpslocation: 'GPS LOCATION',
        str_preview: 'Preview',
        str_retake: 'Re-Take/Upload',
        str_delete: 'Delete',
        str_details: 'Details',
        str_deletephoto: 'Delete Photo!',
        str_deletephotodesc: 'Are you sure you want to delete this photo?',
        str_cancel: 'Cancel',
        str_yesdelete: 'Yes,Delete',
        str_error: 'Error',
        str_ok: 'Ok',
        str_errFirstname: 'Please Enter FIRST NAME',
        str_errMiddlename: 'Please Enter MIDDLE NAME',
        str_errLastname: 'Please Enter LAST NAME',
        str_errMobileNumber: 'Please Enter MOBILE NUMBER',
        str_errvalidMobileNumber: 'Please Enter Valid MOBILE NUMBER',
        str_errCustCatg: 'Please Select CUSTOMER CATEGORY',
        str_plsenter: 'Please Enter ',
        str_plsentervalid: 'Please Enter Valid ',
        str_plsselect: 'Please Select ',
        str_mulfive: 'in Multiple of 5000 ',
      },
      ta: {
        first: 'comment allez vous',
        second: 'je vais bien',
        eng_unableToConnectToServer: 'Unable to connect to server'
      },
}]
  
